### ISSUE TITLE
UnauthorizedError: Unable to login to system using the credentials provided

### ISSUE THREAD

**Issue by Daehnie** [jeroenterheerdt/python-egardia#13]
Hello Jeroen,

I have problems with my Egardia. Every time I want to set the alarm, I need two attempts to activate it. The same if I want to disable the alarm. Now I've run the test_egardiadevice.py script to show you the output. It seems the the Egardia goes after a while in a kind of rest state (after an hour) and if I want to set the alarm then, as I said, I need two attempts. If you have managed to set the alarm, the alarm system works quite normally.

test_egardiadevice.py:
homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages/pythonegardia $ python3 test_egardiadevice.py 192.168.178.35 80 Username Password GATE-01
Traceback (most recent call last):
  File "test_egardiadevice.py", line 35, in <module>
    main()
  File "test_egardiadevice.py", line 30, in main
    eg = e.EgardiaDevice(host, port, username, password, "", version)
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 45, in __init__
    self._sensors = self.getsensors()
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 96, in getsensors
    raise UnauthorizedError('Unable to login to system using the credentials provided')
egardiadevice.UnauthorizedError: 'Unable to login to system using the credentials provided'

homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages/pythonegardia $ python3 test_egardiadevice.py 192.168.178.35 80 Username Password GATE-01
getstate output  DISARM
getsensors output  {'3': {'zone': '3', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'battery': '', 'no': '3', 'area': '1', 'name': 'Gaeste-WC', 'tamp': '', 'attr': 'Burglar'}, '6': {'zone': '7', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'battery': '', 'no': '6', 'area': '1', 'name': 'Kueche', 'tamp': '', 'attr': 'Burglar'}, '9': {'zone': '10', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'battery': '', 'no': '9', 'area': '1', 'name': 'Haustuer', 'tamp': '', 'attr': 'Entry'}, '8': {'zone': '9', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'battery': '', 'no': '8', 'area': '1', 'name': 'Arbeitszimmer', 'tamp': '', 'attr': 'Burglar'}, '7': {'zone': '8', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'battery': '', 'no': '7', 'area': '1', 'name': 'Ylvie', 'tamp': '', 'attr': 'Burglar'}, '11': {'zone': '12', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'battery': '', 'no': '11', 'area': '1', 'name': 'Essecke', 'tamp': '', 'attr': 'Burglar'}, '4': {'zone': '4', 'bypass': 'No', 'cond': '', 'type': 'IR Sensor', 'battery': '', 'no': '4', 'area': '1', 'name': 'Wohnzimmer', 'tamp': '', 'attr': 'Entry'}, '10': {'zone': '11', 'bypass': 'No', 'cond': '', 'type': 'Door Contact', 'battery': '', 'no': '10', 'area': '1', 'name': 'Wohnzimmer', 'tamp': '', 'attr': 'Burglar'}}

Here's the Log of my Panel. At 12:45:48 it's my first try of this script. 12:46:00 the second one.
![bildschirmfoto-20180117125927-1648x158](https://user-images.githubusercontent.com/32060700/35041855-8c828640-fb86-11e7-98cb-ab7fadb802e1.png)

**Comment by jeroenterheerdt** [comment]
this is weird. I have a GATE-01 too but I do not see this behavior. Is your router doing something weird here? I.E. closing off a connection when not active? I have seen before that Egardia does not allow you to log in all the time, but simply restarting HASS seems to resolve the problem. After updating HASS I need to restart it twice since after the first restart I get the error you show above - it is resolved by restarting. I never have to change status twice to get it to pick it up.

**Comment by Daehnie** [comment]
Yes, I have to restart it twice, too. After first restart HASS can't setting my Egardia up:

2018-01-17 14:08:42 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.egardia
2018-01-17 14:08:42 INFO (Thread-4) [pythonegardia.egardiadevice] Egardia doRequest, type: GET, url: http://192.168.178.35:80/action/sensorListGet, payload: None, auth=(Daehnie,****)
2018-01-17 14:08:43 ERROR (Thread-4) [homeassistant.components.alarm_control_panel.egardia] Unable to authorize. Wrong password or username

**Comment by jeroenterheerdt** [comment]
@Daehnie I will see if I can retry the auth to get rid of this. Any other issues?

**Comment by Daehnie** [comment]
Thank you. No other Issues, but can I see my Sensorlist in HASS now?

**Comment by jeroenterheerdt** [comment]
no, the sensorlist is not yet supported, sorry.

**Comment by Daehnie** [comment]
Ah Ok...no problem.

**Comment by jeroenterheerdt** [comment]
@Daehnie I made a quick fix that seems to resolve the error on my end - can you pull and rerun `test_egardiadevice` to see if you get any errors related to unauthorized?

**Comment by Daehnie** [comment]
Wow... I will Test it in the evening or tomorrow.

**Comment by Daehnie** [comment]
It seems, that it works....no unauthorized failure.

homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages/pythonegardia $ python3 test_egardiadevice.py 192.168.178.35 80 username password GATE-01
getstate output  ARM
getsensors output  {'4': {'cond': '', 'tamp': '', 'attr': 'Entry', 'battery': '', 'name': 'Wohnzimmer', 'bypass': 'No', 'area': '1', 'no': '4', 'type': 'IR Sensor', 'zone': '4'}, '11': {'cond': '', 'tamp': '', 'attr': 'Burglar', 'battery': '', 'name': 'Essecke', 'bypass': 'No', 'area': '1', 'no': '11', 'type': 'Door Contact', 'zone': '12'}, '9': {'cond': '', 'tamp': '', 'attr': 'Entry', 'battery': '', 'name': 'Haustuer', 'bypass': 'No', 'area': '1', 'no': '9', 'type': 'Door Contact', 'zone': '10'}, '3': {'cond': '', 'tamp': '', 'attr': 'Burglar', 'battery': '', 'name': 'Gaeste-WC', 'bypass': 'No', 'area': '1', 'no': '3', 'type': 'Door Contact', 'zone': '3'}, '6': {'cond': '', 'tamp': '', 'attr': 'Burglar', 'battery': '', 'name': 'Kueche', 'bypass': 'No', 'area': '1', 'no': '6', 'type': 'Door Contact', 'zone': '7'}, '7': {'cond': '', 'tamp': '', 'attr': 'Burglar', 'battery': '', 'name': 'Ylvie', 'bypass': 'No', 'area': '1', 'no': '7', 'type': 'Door Contact', 'zone': '8'}, '10': {'cond': '', 'tamp': '', 'attr': 'Burglar', 'battery': '', 'name': 'Wohnzimmer', 'bypass': 'No', 'area': '1', 'no': '10', 'type': 'Door Contact', 'zone': '11'}, '8': {'cond': '', 'tamp': '', 'attr': 'Burglar', 'battery': '', 'name': 'Arbeitszimmer', 'bypass': 'No', 'area': '1', 'no': '8', 'type': 'Door Contact', 'zone': '9'}}

**Comment by jeroenterheerdt** [comment]
Perfect, you have GATE-02 or - 01? And you have only door contacts and IR sensors right?

**Comment by Daehnie** [comment]
I've an GATE-01! Yes, that's right... only door contacts and IR sensor!

**Comment by jeroenterheerdt** [comment]
perfect, thanks. I'll close the issue now since it is resolved.

**Comment by Daehnie** [comment]
After restart of HASS it can't be setting up my Egardia:

2018-01-18 17:45:07 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.egardia
2018-01-18 17:45:07 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up platform egardia
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 400, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/egardia.py", line 68, in setup_platform
    from pythonegardia import egardiaserver
ImportError: cannot import name 'egardiaserver'

**Comment by Daehnie** [comment]
@jeroenterheerdt 

Ähm, with new egadiadevice.py I can't arm my Egardia Panel in HASS:

2018-01-18 19:04:25 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=alarm_control_panel, service_call_id=1976332976-7, service=alarm_arm_home, service_data=entity_id=alarm_control_panel.egardia, code=>
2018-01-18 19:04:25 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall alarm_control_panel.alarm_arm_home: entity_id=['alarm_control_panel.egardia'], code=>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/__init__.py", line 140, in async_alarm_service_handler
    yield from getattr(alarm, method)(code)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/egardia.py", line 206, in alarm_arm_home
    self._egardiasystem.alarm_arm_home()
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 171, in alarm_arm_home
    req = self.sendcondition(1)
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 191, in sendcondition
    req = self.doRequestWithRetry('POST', 'panelCondPost', payload)
AttributeError: 'EgardiaDevice' object has no attribute 'doRequestWithRetry'

**Comment by Daehnie** [comment]
Latest working commit is f11df1f  with egardiadevice.py and egardiaserver.py.

**Comment by jeroenterheerdt** [comment]
Hmm, did 'test_egardiadevice.py' work or not?

**Comment by Daehnie** [comment]
test_egardiadevice.py is working! But I can't arm or disarm my Panel over HASS anymore.

2018-01-19 07:37:11 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=alarm_control_panel, service_call_id=1973293712-5, service=alarm_disarm, service_data=code=, entity_id=alarm_control_panel.egardia>
2018-01-19 07:37:11 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall alarm_control_panel.alarm_disarm: code=, entity_id=['alarm_control_panel.egardia']>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/__init__.py", line 140, in async_alarm_service_handler
    yield from getattr(alarm, method)(code)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/egardia.py", line 198, in alarm_disarm
    self._egardiasystem.alarm_disarm()
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 172, in alarm_disarm
    req = self.sendcondition(4)
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 201, in sendcondition
    req = self.doRequestWithRetry('POST', 'panelCondPost', payload)
AttributeError: 'EgardiaDevice' object has no attribute 'doRequestWithRetry'
^C


homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages/pythonegardia $ python3 test_egardiadevice.py 192.168.178.35 80 Daehnie EASports1428 GATE-01
getstate output  ARM
getsensors output  {'6': {'attr': 'Burglar', 'bypass': 'No', 'zone': '7', 'type': 'Door Contact', 'name': 'Kueche', 'no': '6', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}, '11': {'attr': 'Burglar', 'bypass': 'No', 'zone': '12', 'type': 'Door Contact', 'name': 'Essecke', 'no': '11', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}, '8': {'attr': 'Burglar', 'bypass': 'No', 'zone': '9', 'type': 'Door Contact', 'name': 'Arbeitszimmer', 'no': '8', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}, '10': {'attr': 'Burglar', 'bypass': 'No', 'zone': '11', 'type': 'Door Contact', 'name': 'Wohnzimmer', 'no': '10', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}, '3': {'attr': 'Burglar', 'bypass': 'No', 'zone': '3', 'type': 'Door Contact', 'name': 'Gaeste-WC', 'no': '3', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}, '4': {'attr': 'Entry', 'bypass': 'No', 'zone': '4', 'type': 'IR Sensor', 'name': 'Wohnzimmer', 'no': '4', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}, '7': {'attr': 'Burglar', 'bypass': 'No', 'zone': '8', 'type': 'Door Contact', 'name': 'Ylvie', 'no': '7', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}, '9': {'attr': 'Entry', 'bypass': 'No', 'zone': '10', 'type': 'Door Contact', 'name': 'Haustuer', 'no': '9', 'battery': '', 'cond': '', 'tamp': '', 'area': '1'}}

**Comment by jeroenterheerdt** [comment]
What did you do? Did you manually overwrite from files? Since it was working before, right?

**Comment by Daehnie** [comment]
Ok, just so we understand each other. I have replaced all files from your current branch: egardiaserver.py/egardiadevice.py and test_egardiadevice.py/test_egardiaserver.py
In this state I can no longer activate the alarm system via Home Assistant, nor deactivate it. See log files above ...
If I now replace the egardiadevice.py and egardiaserver.py from the branch f11df1f everything works again.

**Comment by Daehnie** [comment]
I see my history without timestamp...
At 17. January I stopped my egardiaserver.service and updated my HASS to 0.61.0.
After that I replaced the test_egardiadevice.py manually. HASS works with my Panel.
At 18. January I have upgraded your package via 'pip3 install --upgrade pythonegardia' and replaced manually egardiaserver.py/egardiadevice.py and test_egardiadevice.py/test_egardiaserver.py, so it is your actually branch.
After that, test_egardiadevice.py works well and HASS can't arm/disarm my Panel.

**Comment by jeroenterheerdt** [comment]
That is to be expected. It is never meant to work this way since Hass looks for a specific version of the component which you just replaced. Revert back. I did not instruct you to do this, I hope.

**Comment by Daehnie** [comment]
Ok, sorry for that. To which files should I return now? Or all the Package?

**Comment by Daehnie** [comment]
I went back to pythonegardia==1.0.26 and replaced egardiadevice.py with new one. Is it correct?

**Comment by jeroenterheerdt** [comment]
That should work - also, pull `test_egardiadevice.py`, these two need to be in sync. Let me know if you need any more help. I would like to you please the output of `test_egardiadevice.py` here.

**Comment by Daehnie** [comment]
Hmm, its the same. 

I removed pythonegardia completely and installed Version 1.0.26. (pip3 install pythonegardia==1.0.26)
(homeassistant) homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages/pythonegardia $ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
aiohttp (2.3.7)
aiohttp-cors (0.6.0)
astral (1.4)
async-timeout (2.0.0)
certifi (2017.11.5)
chardet (3.0.4)
colorlog (3.0.1)
distro (1.2.0)
enum-compat (0.0.2)
fuzzywuzzy (0.16.0)
gTTS-token (1.1.1)
home-assistant-frontend (20180112.0)
homeassistant (0.61.0)
idna (2.6)
Jinja2 (2.10)
MarkupSafe (1.0)
multidict (4.0.0)
mutagen (1.39)
netdisco (1.2.3)
netifaces (0.10.6)
phue (1.0)
pip (9.0.1)
pkg-resources (0.0.0)
PlexAPI (3.0.5)
**pythonegardia (1.0.26)**
pytz (2017.3)
PyYAML (3.12)
requests (2.18.4)
setuptools (33.1.1)
six (1.11.0)
SQLAlchemy (1.2.0)
tqdm (4.19.5)
typing (3.6.2)
ua-parser (0.7.3)
urllib3 (1.22)
user-agents (1.1.0)
voluptuous (0.10.5)
websocket-client (0.46.0)
xmltodict (0.11.0)
yarl (0.18.0)
zeroconf (0.19.1)

After that I replaced egardiadevice.py and test_egardiadevice.py from actually branch.
I cloned (git clone https://github.com/jeroenterheerdt/python-egardia.git) it to tmp and copied both files to /srv/homeassistant/lib/python3.5/site-packages/pythonegardia.

(homeassistant) homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages/pythonegardia $ ls -l
insgesamt 48
-rw-r--r-- 1 homeassistant homeassistant 8303 Jan 19 09:23 **egardiadevice.py**
-rw-r--r-- 1 homeassistant homeassistant 7087 Jan 19 09:21 egardiadevice.py.orig
-rw-r--r-- 1 homeassistant homeassistant 3563 Jan 19 09:10 egardiaserver.py
-rwxr-xr-x 1 homeassistant homeassistant  223 Dez  5 10:09 egardiaserver.sh
-rw-r--r-- 1 homeassistant homeassistant    2 Jan 19 09:10 __init__.py
drwxr-xr-x 2 homeassistant homeassistant 4096 Jan 19 09:23 __pycache__
-rw-r--r-- 1 homeassistant homeassistant 1116 Jan 19 11:21 **test_egardiadevice.py**
-rw-r--r-- 1 homeassistant homeassistant 1116 Jan 19 11:21 test_egardiadevice.py.orig
-rw-r--r-- 1 homeassistant homeassistant 1119 Jan 19 09:10 test_egardiaserver.py

(homeassistant) homeassistant@hassbian:/srv/homeassistant/lib/python3.5/site-packages/pythonegardia $ python3 test_egardiadevice.py 192.168.178.35 80 username password GATE-01
getstate output  DISARM
getsensors output  {'4': {'attr': 'Entry', 'tamp': '', 'zone': '4', 'type': 'IR Sensor', 'cond': '', 'name': 'Wohnzimmer', 'no': '4', 'area': '1', 'battery': '', 'bypass': 'No'}, '7': {'attr': 'Burglar', 'tamp': '', 'zone': '8', 'type': 'Door Contact', 'cond': '', 'name': 'Ylvie', 'no': '7', 'area': '1', 'battery': '', 'bypass': 'No'}, '11': {'attr': 'Burglar', 'tamp': '', 'zone': '12', 'type': 'Door Contact', 'cond': '', 'name': 'Essecke', 'no': '11', 'area': '1', 'battery': '', 'bypass': 'No'}, '3': {'attr': 'Burglar', 'tamp': '', 'zone': '3', 'type': 'Door Contact', 'cond': '', 'name': 'Gaeste-WC', 'no': '3', 'area': '1', 'battery': '', 'bypass': 'No'}, '9': {'attr': 'Entry', 'tamp': '', 'zone': '10', 'type': 'Door Contact', 'cond': '', 'name': 'Haustuer', 'no': '9', 'area': '1', 'battery': '', 'bypass': 'No'}, '6': {'attr': 'Burglar', 'tamp': '', 'zone': '7', 'type': 'Door Contact', 'cond': '', 'name': 'Kueche', 'no': '6', 'area': '1', 'battery': '', 'bypass': 'No'}, '8': {'attr': 'Burglar', 'tamp': '', 'zone': '9', 'type': 'Door Contact', 'cond': '', 'name': 'Arbeitszimmer', 'no': '8', 'area': '1', 'battery': '', 'bypass': 'No'}, '10': {'attr': 'Burglar', 'tamp': '', 'zone': '11', 'type': 'Door Contact', 'cond': '', 'name': 'Wohnzimmer', 'no': '10', 'area': '1', 'battery': '', 'bypass': 'No'}}

But Hass gives me still the same Error if I arm my Panel:
2018-01-19 11:28:23 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall alarm_control_panel.alarm_arm_home: code=, entity_id=['alarm_control_panel.egardia']>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/__init__.py", line 140, in async_alarm_service_handler
    yield from getattr(alarm, method)(code)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/egardia.py", line 206, in alarm_arm_home
    self._egardiasystem.alarm_arm_home()
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 181, in alarm_arm_home
    req = self.sendcondition(1)
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 201, in sendcondition
    req = self.doRequestWithRetry('POST', 'panelCondPost', payload)
AttributeError: 'EgardiaDevice' object has no attribute 'doRequestWithRetry'

what am I doing wrong?

**Comment by jeroenterheerdt** [comment]
@Daehnie I found a bug, sorry. In the latest commit I fixed it (https://github.com/jeroenterheerdt/python-egardia/commit/ab217aff0e618232dcc116fe87120e7580aa81e4). Please pull `egardiadevice.py` and overwrite it. Let me know if it is resolved.

**Comment by Daehnie** [comment]
@jeroenterheerdt 
Unfortunately, no:

2018-01-19 17:19:18 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: service_data=code=, entity_id=alarm_control_panel.egardia, domain=alarm_control_panel, service_call_id=1976640144-5, service=alarm_arm_home>
2018-01-19 17:19:18 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall alarm_control_panel.alarm_arm_home: code=, entity_id=['alarm_control_panel.egardia']>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/core.py", line 1010, in _event_to_service_call
    yield from service_handler.func(service_call)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/__init__.py", line 140, in async_alarm_service_handler
    yield from getattr(alarm, method)(code)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/egardia.py", line 206, in alarm_arm_home
    self._egardiasystem.alarm_arm_home()
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 196, in alarm_arm_home
    req = self.sendcondition(1)
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 216, in sendcondition
    req = self.dorequestwithretry('POST', 'panelCondPost', payload)
  File "/srv/homeassistant/lib/python3.5/site-packages/pythonegardia/egardiadevice.py", line 67, in dorequestwithretry
    for i in range(maxretries+1):
TypeError: unsupported operand type(s) for +: 'dict' and 'int'


 test_egardiadevice.py passed!

**Comment by jeroenterheerdt** [comment]
@Daehnie I have expanded the tests run by `test_egardiadevice.py` to include changing the status of the alarm. Please pull the latest commit (https://github.com/jeroenterheerdt/python-egardia/commit/1b0a853396ab51a5dea5e9516bfc9cf6a250bab9) run it (using python version 3 otherwise it will tell you to). Please share the output with me. It should work since we have the exact same version of the alarm, but you never know.

**Comment by Daehnie** [comment]
@jeroenterheerdt 
I've ever used Python3. :-) 
Output of test_egardiadevice.py:
getstate output  DISARM
getsensors output  {'3': {'cond': '', 'battery': '', 'attr': 'Burglar', 'tamp': '', 'bypass': 'No', 'type': 'Door Contact', 'area': '1', 'id': '3', 'zone': '3', 'name': 'Gaeste-WC'}, '9': {'cond': '', 'battery': '', 'attr': 'Entry', 'tamp': '', 'bypass': 'No', 'type': 'Door Contact', 'area': '1', 'id': '9', 'zone': '10', 'name': 'Haustuer'}, '7': {'cond': '', 'battery': '', 'attr': 'Burglar', 'tamp': '', 'bypass': 'No', 'type': 'Door Contact', 'area': '1', 'id': '7', 'zone': '8', 'name': 'Ylvie'}, '10': {'cond': '', 'battery': '', 'attr': 'Burglar', 'tamp': '', 'bypass': 'No', 'type': 'Door Contact', 'area': '1', 'id': '10', 'zone': '11', 'name': 'Wohnzimmer'}, '6': {'cond': '', 'battery': '', 'attr': 'Burglar', 'tamp': '', 'bypass': 'No', 'type': 'Door Contact', 'area': '1', 'id': '6', 'zone': '7', 'name': 'Kueche'}, '11': {'cond': '', 'battery': '', 'attr': 'Burglar', 'tamp': '', 'bypass': 'No', 'type': 'Door Contact', 'area': '1', 'id': '11', 'zone': '12', 'name': 'Essecke'}, '8': {'cond': '', 'battery': '', 'attr': 'Burglar', 'tamp': '', 'bypass': 'No', 'type': 'Door Contact', 'area': '1', 'id': '8', 'zone': '9', 'name': 'Arbeitszimmer'}, '4': {'cond': '', 'battery': '', 'attr': 'Entry', 'tamp': '', 'bypass': 'No', 'type': 'IR Sensor', 'area': '1', 'id': '4', 'zone': '4', 'name': 'Wohnzimmer'}}
------------
IMPORTANT: continuing passed this point will arm and disarm your alarm!
Press y to ARM your alarm y
Sent arm command to alarm, waiting 10 seconds...
getstate output (should be ARM)  ARM
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  DISARM
Press y to HOME ARM your alarm y
Sent home arm command to alarm, waiting 10 seconds...
getstate output (should be HOME)  HOME
Press y to DISARM your alarm y
Sent disarm command to alarm, waiting 10 seconds...
getstate output (should be DISARM)  DISARM
Tests completed

In HASS it works also. Well Done!!! I would be very happy if it works tonight without setting the alarm twice. I let u know....

**Comment by jeroenterheerdt** [comment]
Happy to hear. Keep me posted!

**Comment by Daehnie** [comment]
It seems to work! Finally... I‘m very happy.

**Comment by jeroenterheerdt** [comment]
Great!
