### ISSUE TITLE
PyPI source is incomplete

### ISSUE THREAD

**Issue by fabaff** [jeroenterheerdt/python-egardia#28]
If the setup process is depending a other files then those files should be part of the source tarball that is published.

```bash
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 2, in <module>
    with open("../README.md", "r") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '../README.md'
```

**Comment by jeroenterheerdt** [comment]
fixed
