### ISSUE TITLE
Status Update 'Arm Home' fails

### ISSUE THREAD

**Issue by Daehnie** [jeroenterheerdt/python-egardia#8]
Hi Jeroen, 

next issue. ;-) 

After running egardiaserver and adding the Servercodes in my configuration.yaml, I can arm and disarm my Egardia Panel. But I after 'arm home' the status doesn't change. 
In the log you can see that I retrieve the correct Servercodes...

First I changed from status 'unknown', because of a restart of egardiaserver, to 'arm away'.
Next from 'arm away' to 'Disarm' and after that switched to 'arm home'.

Home Assistant: 0.55.1
pythonegardia (1.0.22)

homeassistantlog:
2017-10-20 19:23:55 INFO (MainThread) [homeassistant.components.http] Serving /api/history/period/2017-10-20T12:17:39.726Z to 31.17.98.7 (auth: True)
2017-10-20 19:24:10 INFO (MainThread) [homeassistant.components.http] Serving /api/history/period/2017-10-20T17:23:55.825Z to 31.17.98.7 (auth: True)
2017-10-20 19:24:12 INFO (MainThread) [homeassistant.components.http] Serving /api/history/period/2017-10-20T17:24:10.757Z to 31.17.98.7 (auth: True)
2017-10-20 19:24:22 INFO (MainThread) [homeassistant.components.http] Serving /api/history/period/2017-10-20T17:24:12.698Z to 31.17.98.7 (auth: True)
2017-10-20 19:24:33 INFO (MainThread) [homeassistant.components.http] Serving /api/events/egardia_system_status to 31.17.98.7 (auth: True)
2017-10-20 19:24:33 INFO (MainThread) [homeassistant.core] Bus:Handling <Event egardia_system_status[R]: status=18340100034D099>
2017-10-20 19:24:39 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=alarm_control_panel.egardia, old_state=<state alarm_control_panel.egardia=unknown; friendly_name=Egardia, code_format=None, changed_by=None @ 2017-10-20T19:05:33.686665+02:00>, new_state=<state alarm_control_panel.egardia=armed_away; friendly_name=Egardia, code_format=None, changed_by=None @ 2017-10-20T19:24:39.907859+02:00>>

2017-10-20 19:24:54 INFO (MainThread) [homeassistant.components.http] Serving /api/events/egardia_system_status to 31.17.98.7 (auth: True)
2017-10-20 19:24:54 INFO (MainThread) [homeassistant.core] Bus:Handling <Event egardia_system_status[R]: status=18140100034BE97>

2017-10-20 19:25:10 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=alarm_control_panel.egardia, old_state=<state alarm_control_panel.egardia=armed_away; friendly_name=Egardia, code_format=None, changed_by=None @ 2017-10-20T19:24:39.907859+02:00>, new_state=<state alarm_control_panel.egardia=disarmed; friendly_name=Egardia, code_format=None, changed_by=None @ 2017-10-20T19:25:10.908767+02:00>>
2017-10-20 19:25:10 INFO (MainThread) [homeassistant.components.http] Serving / to 31.17.98.7 (auth: False)
2017-10-20 19:25:11 INFO (MainThread) [homeassistant.components.http] Serving /api/websocket to 31.17.98.7 (auth: False)
2017-10-20 19:25:11 INFO (MainThread) [homeassistant.components.http] Serving /api/themes to 31.17.98.7 (auth: True)

2017-10-20 19:25:54 INFO (MainThread) [homeassistant.components.http] Serving /api/events/egardia_system_status to 31.17.98.7 (auth: True)
2017-10-20 19:25:54 INFO (MainThread) [homeassistant.core] Bus:Handling <Event egardia_system_status[R]: status=1834560003411A3>

2017-10-20 19:26:06 INFO (MainThread) [homeassistant.components.http] Serving /api/history/period/2017-10-19T17:26:06.254Z to 31.17.98.7 (auth: True)
2017-10-20 19:26:06 ERROR (Thread-13) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/egardia.py", line 124, in handle_system_status_event
    self.parsestatus(status)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel/egardia.py", line 157, in parsestatus
    if status.upper() == k][0])
IndexError: list index out of range

2017-10-20 19:26:24 INFO (MainThread) [homeassistant.components.http] Serving /api/events/egardia_system_status to 31.17.98.7 (auth: True)
2017-10-20 19:26:24 INFO (MainThread) [homeassistant.core] Bus:Handling <Event egardia_system_status[R]: status=18140100034BE97>

configuration.yaml:
# Egardia
alarm_control_panel:
  - platform: egardia
    host: 192.168.178.35
    username: Username
    password: Password
    report_server_enabled: True
    report_server_port: 52010
    report_server_codes:
      arm: 18340100034D099
      armhome: 1834560003411A3
      disarm: 18140100034BE97
      triggered: 18113000011AE91

Best regards, 

Dennis

**Comment by Daehnie** [comment]
Hey, 

I've found the issue!

In `egardia.py` the states are:

STATES = {
    'ARM': STATE_ALARM_ARMED_AWAY,
    'DAY HOME': STATE_ALARM_ARMED_HOME,
    'DISARM': STATE_ALARM_DISARMED,
    'HOME': STATE_ALARM_ARMED_HOME,
    'TRIGGERED': STATE_ALARM_TRIGGERED,
    'UNKNOWN': STATE_UNKNOWN,
}

But in your description [https://home-assistant.io/components/alarm_control_panel.egardia/](url) it is described differently:

  - platform: egardia
    host: YOUR_HOST
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
 report_server_enabled: True
 report_server_port: PORT_OF_EGARDIASERVER (85 as per the instructions above)
 report_server_codes:
   arm: XXXXXXXXXXXXXXXX, XXXXXXXXXXXXXXXX
   disarm: XXXXXXXXXXXXXXXX, XXXXXXXXXXXXXXXX
   armhome: XXXXXXXXXXXXXXXX
   triggered: XXXXXXXXXXXXXXXX, XXXXXXXXXXXXXXXX, XXXXXXXXXXXXXXXX
   ignore: XXXXXXXXXXXXXXXX

Also in configuration.yaml, `armhome` must be `day home` or `home`!?
 I've tested it with `home` and I have received the correct feedback and status switched to armed_home.

**Comment by jeroenterheerdt** [comment]
huh - this is weird. Might be that home assistant has changed the names of alarm states. I will investigate. Thanks for reporting.

**Comment by jeroenterheerdt** [comment]
I do not see the same issue here (most probably I do not understand where to look). Are you saying the issue is with the armhome status only? I hardly use that so maybe I overlooked it. When you changed 'armhome' in configuration.yaml to 'home' did that solve your problem or did you make more changes?

**Comment by Daehnie** [comment]
Hi, I had the issue only with armhome! 
And yes, I changed only 'armhome' in my configuration.yaml to 'home' and it works for me pretty well!

I saw different states in egardia.py (located in /srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/alarm_control_panel)

STATES = {
'ARM': STATE_ALARM_ARMED_AWAY,
'DAY HOME': STATE_ALARM_ARMED_HOME,
'DISARM': STATE_ALARM_DISARMED,
'HOME': STATE_ALARM_ARMED_HOME,
'TRIGGERED': STATE_ALARM_TRIGGERED,
'UNKNOWN': STATE_UNKNOWN,
}

So, I changed 'armhome' in my configuration.yaml to 'home' and it works without faults in homeassistant.log. 
It have to be worked with 'day home', but I haven't it tested!

Here's my configuration.yaml:
# Egardia
alarm_control_panel:
  - platform: egardia
    host: 192.168.178.35
    username: usernamen
    password: password
    report_server_enabled: True
    report_server_port: 52010
    report_server_codes:
      arm: 18340100034D099, 18340000006C697, 18340000001C192, 18340700001EB99, 18340700002EC9A
      home: 1834560003411A3, 183456000060DA2, 18345600001089D, 18345600001089D, 18345600002099E
      disarm: 18140100034BE97, 18140000006B495, 18140000001AF90, 18140700001D997, 18140700002DA98
      triggered: 18113000011AE91
      ignore: 18160200000CA93

**Comment by jeroenterheerdt** [comment]
Thanks! I'll update the docs on this.
